version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1Gm
      TERM: dumb

    steps:
      - checkout

      - run: gradle clean build

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/test/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/test-results/test/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/test
